apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
spec:
  selector:
    matchLabels:
      app: a
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: a
        version: v1
    spec:
      containers:
        - name: a
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://x.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
spec:
  selector:
    matchLabels:
      app: b
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: b
        version: v1
    spec:
      containers:
        - name: b
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://x.alpha:8888/status,http://y.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
spec:
  selector:
    matchLabels:
      app: c
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: c
        version: v1
    spec:
      containers:
        - name: c
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://y.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  selector:
    matchLabels:
      app: d
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: d
        version: v1
    spec:
      containers:
        - name: d
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://y.alpha:8888/status,http://z.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e
spec:
  selector:
    matchLabels:
      app: e
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: e
        version: v1
    spec:
      containers:
        - name: e
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://z.alpha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x
spec:
  selector:
    matchLabels:
      app: x
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: x
        version: v1
    spec:
      containers:
        - name: x
          image: lucasponce/server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;404,1"
---
apiVersion: v1
kind: Service
metadata:
  name: x
  labels:
    app: x
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "y"
spec:
  selector:
    matchLabels:
      app: "y"
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: "y"
        version: v1
    spec:
      containers:
        - name: "y"
          image: lucasponce/server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;500,1"
---
apiVersion: v1
kind: Service
metadata:
  name: "y"
  labels:
    app: "y"
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: "y"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: z
spec:
  selector:
    matchLabels:
      app: z
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: z
        version: v1
    spec:
      containers:
        - name: z
          image: lucasponce/server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,8;201,1;202,1"
---
apiVersion: v1
kind: Service
metadata:
  name: z
  labels:
    app: z
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: z
