apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
spec:
  selector:
    matchLabels:
      app: a
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: a
        version: v1
    spec:
      containers:
        - name: a
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://b.betha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
spec:
  selector:
    matchLabels:
      app: b
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: b
        version: v1
    spec:
      containers:
        - name: b
          image: lucasponce/server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;404,1"
---
apiVersion: v1
kind: Service
metadata:
  name: b
  labels:
    app: b
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
spec:
  selector:
    matchLabels:
      app: c
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: c
        version: v1
    spec:
      containers:
        - name: c
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://d.betha:8888/status"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  selector:
    matchLabels:
      app: d
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: d
        version: v1
    spec:
      containers:
        - name: d
          image: lucasponce/server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;500,1"
---
apiVersion: v1
kind: Service
metadata:
  name: d
  labels:
    app: d
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e
spec:
  selector:
    matchLabels:
      app: e
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: e
        version: v1
    spec:
      containers:
        - name: e
          image: lucasponce/client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: SERVER_URL
              value: "http://b.betha:8888/status,http://d.betha:8888/status"